### ISSUE TITLE
NET6Migrator doesn't work with the latest TShock NET6 beta

### ISSUE THREAD

**Issue by MasterSlenderTR** [DeathCradle/TShock.Plugins.Net6Migrator#1]
![unknown](https://user-images.githubusercontent.com/50411937/187861748-b23066b3-9514-420c-a715-dc3b60f17efb.png)

**Comment by SignatureBeef** [comment]
tshock beta needs an update since it's using an older version. you can use the launcher here for now instead since the version is paired, or use an older revision where it matches.

however keep in mind that this still isn't a fix-all solution - some plugins still may need to be recompiled manually.
i'll keep this open for now as a remember to upgrade this in the coming weeks due to the new modframework 1.1.0-alpha build that the entire stack will be upgraded to.

**Comment by MasterSlenderTR** [comment]
How do I use the launcher? it just crashes on me after it downloads some plugins.
![Untitled](https://user-images.githubusercontent.com/50411937/188330068-5fa7a41d-af72-4c76-9105-65e5fb227c48.png)

**Comment by MasterSlenderTR** [comment]
Fyi, I just upgraded to latest tshock net 6 beta that was published 6 hour ago but now tshock entirely stopped loading mods from modifications folder
![Untitled](https://user-images.githubusercontent.com/50411937/188495800-1c094485-5b90-4647-98dc-c582c3a1e50b.png)

**Comment by SignatureBeef** [comment]
a fix will be out later today.

**Comment by SignatureBeef** [comment]
should be fixed.

![image](https://user-images.githubusercontent.com/776327/188611488-4952137f-ccea-4015-9d1b-15ce66f7996d.png)

**Comment by MasterSlenderTR** [comment]
I upgraded to that build and it still doesn't load mods for me.
![Untitled](https://user-images.githubusercontent.com/50411937/188625047-d116b962-37db-4526-9e5a-91a7f229e346.png)

**Comment by aarvndhNG** [comment]
@MasterSlenderTR hi
